# Generated by Django 4.0.3 on 2022-05-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
