# Generated by Django 4.0.3 on 2022-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_duration_reponse_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='images',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
