# Generated by Django 4.0.3 on 2022-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
