# Generated by Django 4.0.3 on 2022-05-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_result_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='backgroundimg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='descreption',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='img_id',
            field=models.IntegerField(null=True),
        ),
    ]
