# Generated by Django 3.2.13 on 2022-06-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_category_backgroundimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descreption',
            new_name='description',
        ),
    ]
