# Generated by Django 3.2.13 on 2022-06-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_rename_descreption_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='backgroundimg',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img_id',
        ),
    ]
