# Generated by Django 3.2.13 on 2022-06-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20220625_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
