# Generated by Django 3.2.13 on 2022-06-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20220627_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='background',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
