# Generated by Django 3.2.13 on 2022-06-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_quiz_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='back1',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='back2',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='back3',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
