# Generated by Django 3.2.13 on 2022-06-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20220629_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='back1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='back2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='back3',
        ),
    ]
