# Generated by Django 3.2.13 on 2022-06-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20220629_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
